name: Validate Markdown Documentation

on:
  push:
    paths:
      - '**/*.md'
      - '!README.md' # Exclude README.md at the root
      - '!.github/**'

jobs:
  check-markdown-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'

    - name: Get modified .md files
      run: echo "::set-output name=modified_md_files::$(git diff --name-only HEAD HEAD~ -- '*.md')"
      id: get-modified-files

    - name: Check Markdown Documentation
      if: always()
      run: node .github/scripts/checkDocs.js ${{ steps.get-modified-files.outputs.modified_md_files }}
