name: Validate Markdown Documentation

on:
  push:
    paths:
      - '**/*.md'
      - '!README.md' # Exclude README.md at the root

jobs:
  check-markdown-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: './'
          fetch-depth: 1 # Fetches only the last commit

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Check Markdown Documentation
        run: node .github/scripts/checkDocs.js
